package spin:up@4.0.0;

/// The full world of a guest targeting an http-trigger
world http-trigger {
  include platform;
  export wasi:http/handler@0.3.0-rc-2026-03-15;
}

/// The full world of a guest targeting a redis-trigger
world redis-trigger {
  include platform;
  export spin:redis/inbound-redis@3.0.0;
}

/// The imports needed for a guest to run on a Spin host
world platform {
  include wasi:cli/imports@0.2.6;
  include wasi:cli/imports@0.3.0-rc-2026-03-15;
  import wasi:http/outgoing-handler@0.2.6;
  import wasi:http/client@0.3.0-rc-2026-03-15;
  @unstable(feature = wasi-otel)
  include wasi:otel/imports@0.2.0-rc.2;
  include fermyon:spin/platform@2.0.0;
  include wasi:keyvalue/imports@0.2.0-draft2;
  import spin:key-value/key-value@3.0.0;
  import spin:mqtt/mqtt@3.0.0;
  import spin:postgres/postgres@3.0.0;
  import spin:postgres/postgres@4.2.0;
  import spin:redis/redis@3.0.0;
  import spin:sqlite/sqlite@3.1.0;
  import spin:variables/variables@3.0.0;
  import wasi:config/store@0.2.0-draft-2024-09-27;
}
